wrapperVersion=3.3.4
distributionType=only-script
# 阿里云镜像（国内加速）
# distributionUrl=https://maven.aliyun.com/repository/public/org/apache/maven/apache-maven/3.8.6/apache-maven-3.8.6-bin.zip
# 官方镜像
# distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.8.6/apache-maven-3.8.6-bin.zip
distributionUrl=https://maven.aliyun.com/repository/public/org/apache/maven/apache-maven/3.8.6/apache-maven-3.8.6-bin.zip
